Add constants for lsp specific error codes
gluon-lang/lsp-types pull request #211
Opened 2021-06-07 18:52 UTC by tamc

This pull request adds constants for LSP specific [error codes](https://microsoft.github.io/language-server-protocol/specifications//specification-3-17/#errorCodes), but not for the ones that are part of the JSON RPC specification.

I can add the JSON RPC ones mentioned in the LSP specification if you think that is appropriate?

2021-06-08 12:28 UTC, Marwes requested changes
Users are probably using a JSON RPC library so any error codes specific to the protocol probably makes more sense there I'd say. So it is likely redundant to also include those here.

2021-06-08 12:28 UTC, Marwes commented on src/error_codes.rs
> +pub const lspReservedErrorRangeStart: i64 = -32899;
Constants in rust should be `SCREAMING_SNAKE_CASE`

2021-06-10 14:13 UTC, tamc commented
Righto. Constants are now screaming snake case.

2021-06-10 16:09 UTC, merged

2021-06-10 16:09 UTC, Marwes commented
Thanks!